### ISSUE TITLE
USGS Catalogue

### ISSUE THREAD

**Issue by Jollyfant** [EIDA/webdc3#10]
Hi guys, we got a report that USGS event catalogue crashes when it is queried:

    Failed to get events: Error 503: Temporarily Unavailable

    Service 'comcat': No answer from URL / <urlopen error [Errno 101] Network is unreachable>. 

    Request:
    http://knmi-orweb-l02p.knmi.ssc-campus.nl/event/comcat?start=2017-08-29&end=2017-09-06&minmag=3&maxmag=10&mindepth=0&maxdepth=999&minlat=-90&minlon=-180&maxlat=90&maxlon=180&format=json&_=1504624463100

    Request Submitted:
    2017-09-05 15:14:22.788554

    Service version:
    2015.035 

Any ideas? Using WebDC3 v1.1 (2017.096).

**Comment by Jollyfant** [comment]
I don't know if this is a config. problem at our end or not. It works @webdc3.eu - what do you think @pevans-gfz/.

**Comment by Jollyfant** [comment]
Anyone @andres-h? Our instance is here:

http://145.23.3.21/webdc3/

**Comment by andres-h** [comment]
See 
http://145.23.3.21/webdc3/wsgi/event/comcat?start=2017-09-14&end=2017-09-22&minmag=3&maxmag=10&mindepth=0&maxdepth=999&minlat=-90&minlon=-180&maxlat=90&maxlon=180&format=json&_=1505994363821

Is http://earthquake.usgs.gov/fdsnws/event/1/query 
(event.service.comcat.baseURL) reachable from your server.

**Comment by andres-h** [comment]
Probably you are using the old comcat settings. Correct is:
```
event.service.comcat.handler = "fdsnws"
event.service.comcat.baseURL = "http://earthquake.usgs.gov/fdsnws/event/1/query"
event.service.comcat.extraParams = "format=text"
```

**Comment by Jollyfant** [comment]
Ok thanks it works now! Will you update the config sample or shall I make a pull?

M

**Comment by Jollyfant** [comment]
https://github.com/EIDA/webdc3/blob/master/wsgi/webinterface.cfg.sample#L79-L81

This one.

**Comment by andres-h** [comment]
Updated now.

**Comment by Jollyfant** [comment]
Fixed in https://github.com/EIDA/webdc3/commit/c60b40eb915fccdebe39cac09a7e88ac375b8afc
