### ISSUE TITLE
An error occured when make webdc3.min.js

### ISSUE THREAD

**Issue by GarryLai** [EIDA/webdc3#24]
When I entered the make command, and it show this error.
What should I do??

> root@sc3training:~# cd /var/www/webinterface
> root@sc3training:/var/www/webinterface# make
> mkdir -p js
> browserify --entry src/main.js --transform [ babelify --presets es2015 --no-comments --minified ] --outfile js/webdc3.min.js
> Error: .presets must be an array, or undefined while parsing file: /var/www/webinterface/src/main.js
>     at assertArray (/var/www/webinterface/node_modules/@babel/core/lib/config/validation/option-assertions.js:150:11)
>     at assertPluginList (/var/www/webinterface/node_modules/@babel/core/lib/config/validation/option-assertions.js:219:15)
>     at Object.keys.forEach.key (/var/www/webinterface/node_modules/@babel/core/lib/config/validation/options.js:107:5)
>     at Array.forEach (<anonymous>)
>     at validateNested (/var/www/webinterface/node_modules/@babel/core/lib/config/validation/options.js:83:21)
>     at validate (/var/www/webinterface/node_modules/@babel/core/lib/config/validation/options.js:74:10)
>     at loadPrivatePartialConfig (/var/www/webinterface/node_modules/@babel/core/lib/config/partial.js:66:50)
>     at Object.loadPartialConfig (/var/www/webinterface/node_modules/@babel/core/lib/config/partial.js:110:18)
>     at transform (/var/www/webinterface/node_modules/babelify/index.js:157:17)
>     at BabelifyStream._flush (/var/www/webinterface/node_modules/babelify/index.js:138:5)
> Makefile:13: recipe for target 'js/webdc3.min.js' failed
> make: *** [js/webdc3.min.js] Error 1

**Comment by andres-h** [comment]
The minified javascript is included, so running make is not required, but in case you modified javascript source, I updated the Makefile to work with newer node versions. Note the [different node packages](https://github.com/EIDA/webdc3/blob/667257a78759b50a8dd7f420e9bceeb1ae80ba39/Makefile#L10).
