### ISSUE TITLE
The same error appear with new version of makefile

### ISSUE THREAD

**Issue by GarryLai** [EIDA/webdc3#25]
The same error appear with new version of makefile.
My npm and all packages are the latest version.

> root@sc3training:/var/www/webinterface# make
> mkdir -p js
> browserify --entry src/main.js --transform [ babelify --presets env --no-comments --minified ] --outfile js/webdc3.min.js
> Error: .presets must be an array, or undefined while parsing file: /var/www/webinterface/src/main.js
>     at assertArray (/var/www/webinterface/node_modules/@babel/core/lib/config/validation/option-assertions.js:150:11)
>     at assertPluginList (/var/www/webinterface/node_modules/@babel/core/lib/config/validation/option-assertions.js:219:15)
>     at Object.keys.forEach.key (/var/www/webinterface/node_modules/@babel/core/lib/config/validation/options.js:107:5)
>     at Array.forEach (<anonymous>)
>     at validateNested (/var/www/webinterface/node_modules/@babel/core/lib/config/validation/options.js:83:21)
>     at validate (/var/www/webinterface/node_modules/@babel/core/lib/config/validation/options.js:74:10)
>     at loadPrivatePartialConfig (/var/www/webinterface/node_modules/@babel/core/lib/config/partial.js:66:50)
>     at Object.loadPartialConfig (/var/www/webinterface/node_modules/@babel/core/lib/config/partial.js:110:18)
>     at transform (/var/www/webinterface/node_modules/babelify/index.js:157:17)
>     at BabelifyStream._flush (/var/www/webinterface/node_modules/babelify/index.js:138:5)
> Makefile:13: recipe for target 'js/webdc3.min.js' failed
> make: *** [js/webdc3.min.js] Error 1
> root@sc3training:/var/www/webinterface#

**Comment by andres-h** [comment]
Please remove the node_modules directory and (re-)install the required modules:

`$ npm install browserify babelify@8 babel-core babel-preset-env`

**Comment by GarryLai** [comment]
Thanks, it worked!

**Comment by Ashish-Toppo** [comment]
thanks man it worked for me, also make sure that in your '.babelrc' file the presets are in an array:
{
'presets': ['@babel/preset-env']
}
