### ISSUE TITLE
An error in arclink

### ISSUE THREAD

**Issue by GarryLai** [EIDA/webdc3#26]
It dlsplay
> Fetching the list of time windows...
> ...done
> Sent 0 requests
> Routing of 3 lines failed

after send a request. I have set the correct address in webinterface.cfg, what should I do next to fix it?

**Comment by andres-h** [comment]
You need correct arclink bindings pointing to your server(s), eg., ~/seiscomp3/etc/key/station_* should contain "arclink:default" and ~/seiscomp3/etc/key/arclink/profile_default should have correct content.

Note that ArcLink will be deprecated soon in favor of FDSNWS. There is an initial version of webdc3 without ArcLink (deployed at BMKG) at https://github.com/andres-h/webdc3/tree/bmkg

**Comment by GarryLai** [comment]
Thanks, it really works.
