### ISSUE TITLE
Does webdc3 support password when using arclink?

### ISSUE THREAD

**Issue by GarryLai** [EIDA/webdc3#28]
Does webdc3 support password for users when using arclink?

**Comment by andres-h** [comment]
Yes, if encryption is enabled, password is generated and sent to user by e-mail when restricted data is requested for the first time. The user ID must be a correct e-mail address for this to work. This method is not webdc3-specific, but works with arclink in general. The data is now encrypted and [must be decrypted by user](http://eida.gfz-potsdam.de/webdc3/help.html).

A simpler workaround is using no encryption, but an "unguessable" (eg., random string) user ID as a "password".

In any case, arclink-access bindings must be configured and the restricted flag must be set in inventory.

**Comment by GarryLai** [comment]
I meam that is there a black for me to enter the password for a user (e.g. admin)?

**Comment by andres-h** [comment]
No, arclink passwords are not supported.

**Comment by GarryLai** [comment]
Thanks for your helping.
