### ISSUE TITLE
Downloaded packages cannot be saved

### ISSUE THREAD

**Issue by jbienkowski** [EIDA/webdc3#32]
This issue has been created on behalf of one of our users:

---

Hi, I am attempting to download meta data from the Orfeus web interface.  I select full response meta data.
The issue is demonstrated in the image I uploaded at the following location.  I took a screen shot of what normally occurs.  Everything appears to complete its course, but station xml files cannot be saved for two or three of the sources.  It doesn't matter how long I wait.  In this example, you can see that I cannot save the file for orfeus, ingv, or resif.

I have also attempted to retrieve station xml files using the fdsn fetch scripts, which works well for me to retrieve mini-seed data, but almost never returns a station xml file that I can actually parse.  Hence, I have been trying to get the station xml files through the web interface, but it is unclear to me what is going on here.

Thanks for any suggestions or help you can provide and also if you need additional information from me.  I am using firefox web browser, and am attempting to download event data for events occurring in 2018 and am just attempting to download BHE, and BHN components at this time.  I am also wanting to download HHE and HHN components, but I always get an error if the request has more than ~1,600 stations found in the query.

![Orfeus_stationXML_files](https://user-images.githubusercontent.com/8037752/76299964-d6c31a80-62b3-11ea-8c6c-67269e749880.jpg)

**Comment by andres-h** [comment]
Click on the bar(s) to see the status. Probably there was just no data 
to save.

**Comment by jbienkowski** [comment]
No response from the user, I am therefore closing this issue. Thanks, @andres-h!
