### ISSUE TITLE
Restricted by default

### ISSUE THREAD

**Issue by jordi-domingo** [EIDA/webdc3#40]
Hi Javier and all,

I just noticed that some of our stations show up as "Restricted and permanent" in WebDC3, while they are not. After looking a bit deeper, I realized that those stations are missing an explicit `<restricted>false</restricted>` field on station level in their inventory.

Looking at `update-metadata.py`, it seems that, by default, the networks and stations are set to restricted unless they have `get('restrictedStatus') == 'open'`.

https://github.com/EIDA/webdc3/blob/master/data/update-metadata.py#L226
https://github.com/EIDA/webdc3/blob/master/data/update-metadata.py#L262

Is that an intentional behavior? Wouldn't make more sense to do it the other way around (open by default)?

Thanks for your time and help!

**Comment by javiquinte** [comment]
Hi @jordi-domingo !
This behaviour has advantages and disadvantages, but at the moment we decided to implement it we prioritised the security of the restricted stations. In a case like the one you described, we can fix it as soon as someone notice the problem.
However, with the other approach, we would have a leak of restricted data that would affect the credibility of the data centre.

**Comment by jordi-domingo** [comment]
Ok, I understand. Does that mean that the code will stay like this?

**Comment by javiquinte** [comment]
Actually I was wrong and have to correct myself. The code will not leak the data as this is controlled by the data centre, not Webdc3.
What it will actually happen is that the user will try to download from a (restricted) station and will receive an error.

**Comment by javiquinte** [comment]
> Ok, I understand. Does that mean that the code will stay like this?

I guess, but we can always discuss it at ETC/EMB level.

**Comment by jordi-domingo** [comment]
Ok, thanks for the feedback! I guess that for now we will add the missing field in those stations.
